UIWebView *view39 = [[UIWebView alloc] initWithFrame:CGRectMake(20.0, 26.0, 240.0, 128.0)];
view39.frame = CGRectMake(20.0, 26.0, 240.0, 128.0);
view39.alpha = 1.000;
view39.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view39.backgroundColor = [UIColor colorWithRed:1.000 green:1.000 blue:1.000 alpha:1.000];
view39.clearsContextBeforeDrawing = YES;
view39.clipsToBounds = YES;
view39.contentMode = UIViewContentModeScaleToFill;
view39.detectsPhoneNumbers = NO;
view39.hidden = NO;
view39.multipleTouchEnabled = YES;
view39.opaque = YES;
view39.scalesPageToFit = YES;
view39.tag = 0;
view39.userInteractionEnabled = YES;

UIView *view35 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view35.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view35.alpha = 1.000;
view35.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view35.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view35.clearsContextBeforeDrawing = NO;
view35.clipsToBounds = NO;
view35.contentMode = UIViewContentModeScaleToFill;
view35.hidden = NO;
view35.multipleTouchEnabled = NO;
view35.opaque = YES;
view35.tag = 0;
view35.userInteractionEnabled = YES;

UITextField *view8 = [[UITextField alloc] initWithFrame:CGRectMake(20.0, 20.0, 97.0, 31.0)];
view8.frame = CGRectMake(20.0, 20.0, 97.0, 31.0);
view8.adjustsFontSizeToFitWidth = YES;
view8.alpha = 1.000;
view8.autocapitalizationType = UITextAutocapitalizationTypeNone;
view8.autocorrectionType = UITextAutocorrectionTypeDefault;
view8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view8.borderStyle = UITextBorderStyleRoundedRect;
view8.clearsContextBeforeDrawing = NO;
view8.clearsOnBeginEditing = YES;
view8.clipsToBounds = NO;
view8.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
view8.contentMode = UIViewContentModeScaleToFill;
view8.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
view8.enabled = YES;
view8.enablesReturnKeyAutomatically = NO;
view8.font = [UIFont fontWithName:@"Helvetica" size:12.000];
view8.hidden = NO;
view8.highlighted = NO;
view8.keyboardAppearance = UIKeyboardAppearanceDefault;
view8.keyboardType = UIKeyboardTypeDefault;
view8.minimumFontSize = 17.000;
view8.multipleTouchEnabled = NO;
view8.opaque = NO;
view8.placeholder = @"zapato";
view8.returnKeyType = UIReturnKeyDefault;
view8.secureTextEntry = NO;
view8.selected = NO;
view8.tag = 0;
view8.text = @"";
view8.textAlignment = UITextAlignmentLeft;
view8.textColor = [UIColor colorWithWhite:0.000 alpha:1.000];
view8.userInteractionEnabled = YES;

UIScrollView *view29 = [[UIScrollView alloc] initWithFrame:CGRectMake(20.0, 350.0, 240.0, 90.0)];
view29.frame = CGRectMake(20.0, 350.0, 240.0, 90.0);
view29.alpha = 1.000;
view29.alwaysBounceHorizontal = NO;
view29.alwaysBounceVertical = NO;
view29.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin;
view29.bounces = YES;
view29.bouncesZoom = NO;
view29.canCancelContentTouches = YES;
view29.clearsContextBeforeDrawing = YES;
view29.clipsToBounds = YES;
view29.contentMode = UIViewContentModeScaleToFill;
view29.delaysContentTouches = YES;
view29.directionalLockEnabled = NO;
view29.hidden = NO;
view29.indicatorStyle = UIScrollViewIndicatorStyleDefault;
view29.maximumZoomScale = 1.000;
view29.minimumZoomScale = 1.000;
view29.multipleTouchEnabled = YES;
view29.opaque = YES;
view29.pagingEnabled = NO;
view29.scrollEnabled = YES;
view29.showsHorizontalScrollIndicator = YES;
view29.showsVerticalScrollIndicator = YES;
view29.tag = 0;
view29.userInteractionEnabled = YES;

UIView *view40 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view40.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view40.alpha = 1.000;
view40.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view40.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view40.clearsContextBeforeDrawing = NO;
view40.clipsToBounds = NO;
view40.contentMode = UIViewContentModeScaleToFill;
view40.hidden = NO;
view40.multipleTouchEnabled = NO;
view40.opaque = YES;
view40.tag = 0;
view40.userInteractionEnabled = YES;

UITableViewCell *view28 = [[UITableViewCell alloc] initWithFrame:CGRectMake(8.0, 284.0, 320.0, 44.0) reuseIdentifier:@"reuseIdentifierString"];
view28.frame = CGRectMake(8.0, 284.0, 320.0, 44.0);
view28.accessoryType = UITableViewCellAccessoryDetailDisclosureButton;
view28.alpha = 1.000;
view28.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view28.backgroundColor = [UIColor colorWithWhite:1.000 alpha:0.000];
view28.clearsContextBeforeDrawing = NO;
view28.clipsToBounds = NO;
view28.contentMode = UIViewContentModeScaleToFill;
view28.font = [UIFont fontWithName:@"Helvetica" size:17.000];
view28.hidden = NO;
view28.hidesAccessoryWhenEditing = YES;
view28.indentationLevel = 0;
view28.indentationWidth = 10.000;
view28.lineBreakMode = UILineBreakModeTailTruncation;
view28.multipleTouchEnabled = NO;
view28.opaque = NO;
view28.selectedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view28.selectionStyle = UITableViewCellSelectionStyleBlue;
view28.showsReorderControl = NO;
view28.tag = 0;
view28.textAlignment = UITextAlignmentLeft;
view28.textColor = [UIColor colorWithRed:0.600 green:0.400 blue:0.200 alpha:1.000];
view28.userInteractionEnabled = YES;

UISlider *view12 = [[UISlider alloc] initWithFrame:CGRectMake(8.0, 101.0, 118.0, 23.0)];
view12.frame = CGRectMake(8.0, 101.0, 118.0, 23.0);
view12.alpha = 1.000;
view12.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view12.clearsContextBeforeDrawing = YES;
view12.clipsToBounds = YES;
view12.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
view12.contentMode = UIViewContentModeScaleToFill;
view12.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
view12.continuous = YES;
view12.enabled = YES;
view12.hidden = NO;
view12.highlighted = NO;
view12.maximumValue = 1.000;
view12.minimumValue = 0.000;
view12.multipleTouchEnabled = YES;
view12.opaque = NO;
view12.selected = NO;
view12.tag = 0;
view12.userInteractionEnabled = YES;
view12.value = 0.500;

UITextView *view33 = [[UITextView alloc] initWithFrame:CGRectMake(20.0, 20.0, 231.0, 209.0)];
view33.frame = CGRectMake(20.0, 20.0, 231.0, 209.0);
view33.alpha = 1.000;
view33.alwaysBounceHorizontal = NO;
view33.alwaysBounceVertical = NO;
view33.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view33.bounces = YES;
view33.bouncesZoom = NO;
view33.canCancelContentTouches = NO;
view33.clearsContextBeforeDrawing = YES;
view33.clipsToBounds = YES;
view33.contentMode = UIViewContentModeScaleToFill;
view33.delaysContentTouches = NO;
view33.directionalLockEnabled = NO;
view33.editable = YES;
view33.font = [UIFont fontWithName:@"Helvetica" size:17.000];
view33.hidden = NO;
view33.indicatorStyle = UIScrollViewIndicatorStyleDefault;
view33.maximumZoomScale = 1.000;
view33.minimumZoomScale = 1.000;
view33.multipleTouchEnabled = YES;
view33.opaque = NO;
view33.pagingEnabled = NO;
view33.scrollEnabled = YES;
view33.showsHorizontalScrollIndicator = NO;
view33.showsVerticalScrollIndicator = YES;
view33.tag = 0;
view33.text = @"Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.";
view33.textAlignment = UITextAlignmentLeft;
view33.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:1.000 alpha:1.000];
view33.userInteractionEnabled = YES;

UIView *view6 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view6.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view6.alpha = 1.000;
view6.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view6.backgroundColor = [UIColor colorWithWhite:0.750 alpha:1.000];
view6.clearsContextBeforeDrawing = NO;
view6.clipsToBounds = NO;
view6.contentMode = UIViewContentModeScaleToFill;
view6.hidden = NO;
view6.multipleTouchEnabled = NO;
view6.opaque = YES;
view6.tag = 0;
view6.userInteractionEnabled = YES;

UITableView *view26 = [[UITableView alloc] initWithFrame:CGRectMake(20.0, 20.0, 253.0, 179.0) style:UITableViewStylePlain];
view26.frame = CGRectMake(20.0, 20.0, 253.0, 179.0);
view26.allowsSelectionDuringEditing = NO;
view26.alpha = 1.000;
view26.alwaysBounceHorizontal = NO;
view26.alwaysBounceVertical = NO;
view26.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view26.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view26.bounces = YES;
view26.bouncesZoom = NO;
view26.canCancelContentTouches = YES;
view26.clearsContextBeforeDrawing = NO;
view26.clipsToBounds = YES;
view26.contentMode = UIViewContentModeScaleToFill;
view26.delaysContentTouches = YES;
view26.directionalLockEnabled = NO;
view26.hidden = NO;
view26.indicatorStyle = UIScrollViewIndicatorStyleDefault;
view26.maximumZoomScale = 1.000;
view26.minimumZoomScale = 1.000;
view26.multipleTouchEnabled = NO;
view26.opaque = NO;
view26.pagingEnabled = NO;
view26.scrollEnabled = YES;
view26.sectionIndexMinimumDisplayRowCount = 0;
view26.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
view26.showsHorizontalScrollIndicator = YES;
view26.showsVerticalScrollIndicator = YES;
view26.tag = 0;
view26.userInteractionEnabled = YES;

UIActivityIndicatorView *view18 = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
view18.frame = CGRectMake(48.0, 334.0, 20.0, 20.0);
view18.alpha = 1.000;
view18.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view18.clearsContextBeforeDrawing = NO;
view18.clipsToBounds = NO;
view18.contentMode = UIViewContentModeScaleToFill;
view18.hidden = NO;
view18.hidesWhenStopped = NO;
view18.multipleTouchEnabled = NO;
view18.opaque = NO;
view18.tag = 0;
view18.userInteractionEnabled = NO;
[view18 startAnimating];

UITableView *view25 = [[UITableView alloc] initWithFrame:CGRectMake(559.0, 25.0, 215.0, 288.0) style:UITableViewStylePlain];
view25.frame = CGRectMake(559.0, 25.0, 215.0, 288.0);
view25.allowsSelectionDuringEditing = NO;
view25.alpha = 1.000;
view25.alwaysBounceHorizontal = NO;
view25.alwaysBounceVertical = NO;
view25.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view25.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view25.bounces = YES;
view25.bouncesZoom = NO;
view25.canCancelContentTouches = YES;
view25.clearsContextBeforeDrawing = NO;
view25.clipsToBounds = YES;
view25.contentMode = UIViewContentModeScaleToFill;
view25.delaysContentTouches = YES;
view25.directionalLockEnabled = NO;
view25.hidden = NO;
view25.indicatorStyle = UIScrollViewIndicatorStyleDefault;
view25.maximumZoomScale = 1.000;
view25.minimumZoomScale = 1.000;
view25.multipleTouchEnabled = NO;
view25.opaque = NO;
view25.pagingEnabled = NO;
view25.scrollEnabled = YES;
view25.sectionIndexMinimumDisplayRowCount = 0;
view25.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
view25.showsHorizontalScrollIndicator = YES;
view25.showsVerticalScrollIndicator = YES;
view25.tag = 0;
view25.userInteractionEnabled = YES;

UISegmentedControl *view20 = [[UISegmentedControl alloc] initWithItems:[NSArray arrayWithObjects:@"First", @"Second", nil]];
view20.frame = CGRectMake(60.0, 125.0, 207.0, 44.0);
view20.alpha = 1.000;
view20.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view20.clearsContextBeforeDrawing = NO;
view20.clipsToBounds = NO;
view20.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
view20.contentMode = UIViewContentModeScaleToFill;
view20.contentVerticalAlignment = UIControlContentVerticalAlignmentTop;
view20.enabled = YES;
view20.hidden = NO;
view20.highlighted = NO;
view20.momentary = NO;
view20.multipleTouchEnabled = NO;
view20.opaque = NO;
view20.segmentedControlStyle = UISegmentedControlStylePlain;
view20.selected = NO;
view20.selectedSegmentIndex = 0;
view20.tag = 0;
view20.userInteractionEnabled = YES;

UILabel *view10 = [[UILabel alloc] initWithFrame:CGRectMake(106.0, 181.0, 155.0, 21.0)];
view10.frame = CGRectMake(106.0, 181.0, 155.0, 21.0);
view10.adjustsFontSizeToFitWidth = YES;
view10.alpha = 1.000;
view10.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view10.backgroundColor = [UIColor colorWithWhite:0.000 alpha:0.000];
view10.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
view10.clearsContextBeforeDrawing = YES;
view10.clipsToBounds = YES;
view10.contentMode = UIViewContentModeScaleToFill;
view10.enabled = YES;
view10.font = [UIFont fontWithName:@"Helvetica" size:17.000];
view10.hidden = NO;
view10.highlightedTextColor = [UIColor colorWithRed:0.000 green:1.000 blue:0.000 alpha:1.000];
view10.lineBreakMode = UILineBreakModeTailTruncation;
view10.minimumFontSize = 10.000;
view10.multipleTouchEnabled = NO;
view10.numberOfLines = 1;
view10.opaque = NO;
view10.shadowColor = [UIColor colorWithRed:1.000 green:0.500 blue:0.000 alpha:1.000];
view10.shadowOffset = CGSizeMake(59.0, 2.0);
view10.tag = 0;
view10.text = @"Label";
view10.textAlignment = UITextAlignmentLeft;
view10.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
view10.userInteractionEnabled = NO;

UIPickerView *view34 = [[UIPickerView alloc] initWithFrame:CGRectMake(0.0, 244.0, 320.0, 216.0)];
view34.frame = CGRectMake(0.0, 244.0, 320.0, 216.0);
view34.alpha = 1.000;
view34.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view34.clearsContextBeforeDrawing = YES;
view34.clipsToBounds = YES;
view34.contentMode = UIViewContentModeScaleToFill;
view34.hidden = NO;
view34.multipleTouchEnabled = YES;
view34.opaque = NO;
view34.showsSelectionIndicator = YES;
view34.tag = 0;
view34.userInteractionEnabled = YES;

UIView *view32 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view32.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view32.alpha = 1.000;
view32.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view32.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view32.clearsContextBeforeDrawing = NO;
view32.clipsToBounds = NO;
view32.contentMode = UIViewContentModeScaleToFill;
view32.hidden = NO;
view32.multipleTouchEnabled = NO;
view32.opaque = YES;
view32.tag = 0;
view32.userInteractionEnabled = YES;

UIView *view14 = [[UIView alloc] initWithFrame:CGRectMake(146.0, 210.0, 160.0, 230.0)];
view14.frame = CGRectMake(146.0, 210.0, 160.0, 230.0);
view14.alpha = 0.641;
view14.autoresizingMask = UIViewAutoresizingFlexibleHeight;
view14.backgroundColor = [UIColor colorWithRed:0.772 green:0.027 blue:0.000 alpha:1.000];
view14.clearsContextBeforeDrawing = NO;
view14.clipsToBounds = YES;
view14.contentMode = UIViewContentModeScaleToFill;
view14.hidden = NO;
view14.multipleTouchEnabled = YES;
view14.opaque = YES;
view14.tag = 12;
view14.userInteractionEnabled = YES;

UISwitch *view13 = [[UISwitch alloc] initWithFrame:CGRectMake(30.0, 165.0, 94.0, 27.0)];
view13.frame = CGRectMake(30.0, 165.0, 94.0, 27.0);
view13.alpha = 1.000;
view13.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view13.clearsContextBeforeDrawing = YES;
view13.clipsToBounds = YES;
view13.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
view13.contentMode = UIViewContentModeScaleToFill;
view13.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
view13.enabled = YES;
view13.hidden = NO;
view13.highlighted = NO;
view13.multipleTouchEnabled = YES;
view13.on = YES;
view13.opaque = NO;
view13.selected = NO;
view13.tag = 0;
view13.userInteractionEnabled = YES;

UIPageControl *view19 = [[UIPageControl alloc] initWithFrame:CGRectMake(49.0, 392.0, 38.0, 36.0)];
view19.frame = CGRectMake(49.0, 392.0, 38.0, 36.0);
view19.alpha = 1.000;
view19.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view19.clearsContextBeforeDrawing = YES;
view19.clipsToBounds = YES;
view19.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
view19.contentMode = UIViewContentModeScaleToFill;
view19.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
view19.currentPage = 0;
view19.defersCurrentPageDisplay = NO;
view19.enabled = YES;
view19.hidden = NO;
view19.hidesForSinglePage = NO;
view19.highlighted = NO;
view19.multipleTouchEnabled = YES;
view19.numberOfPages = 3;
view19.opaque = NO;
view19.selected = NO;
view19.tag = 0;
view19.userInteractionEnabled = YES;

UIImageView *view27 = [[UIImageView alloc] initWithFrame:CGRectMake(68.0, 148.0, 240.0, 128.0)];
view27.frame = CGRectMake(68.0, 148.0, 240.0, 128.0);
view27.alpha = 1.000;
view27.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view27.clearsContextBeforeDrawing = NO;
view27.clipsToBounds = NO;
view27.contentMode = UIViewContentModeCenter;
view27.hidden = NO;
view27.image = nil;
view27.multipleTouchEnabled = NO;
view27.opaque = NO;
view27.tag = 0;
view27.userInteractionEnabled = NO;

UIProgressView *view11 = [[UIProgressView alloc] initWithProgressViewStyle:UIProgressViewStyleDefault];
view11.frame = CGRectMake(52.0, 259.0, 150.0, 9.0);
view11.alpha = 1.000;
view11.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view11.clearsContextBeforeDrawing = YES;
view11.clipsToBounds = YES;
view11.contentMode = UIViewContentModeScaleToFill;
view11.hidden = NO;
view11.multipleTouchEnabled = YES;
view11.opaque = NO;
view11.progress = 0.500;
view11.progressViewStyle = UIProgressViewStyleDefault;
view11.tag = 0;
view11.userInteractionEnabled = YES;

UIView *view23 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view23.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view23.alpha = 1.000;
view23.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view23.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view23.clearsContextBeforeDrawing = NO;
view23.clipsToBounds = NO;
view23.contentMode = UIViewContentModeScaleToFill;
view23.hidden = NO;
view23.multipleTouchEnabled = NO;
view23.opaque = YES;
view23.tag = 0;
view23.userInteractionEnabled = YES;

UIButton *view9 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
view9.frame = CGRectMake(167.0, 65.0, 72.0, 37.0);
view9.adjustsImageWhenDisabled = YES;
view9.adjustsImageWhenHighlighted = YES;
view9.alpha = 1.000;
view9.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view9.clearsContextBeforeDrawing = NO;
view9.clipsToBounds = NO;
view9.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
view9.contentMode = UIViewContentModeScaleToFill;
view9.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
view9.enabled = YES;
view9.font = [UIFont fontWithName:@"Helvetica-Bold" size:15.000];
view9.hidden = NO;
view9.highlighted = NO;
view9.multipleTouchEnabled = NO;
view9.opaque = NO;
view9.reversesTitleShadowWhenHighlighted = NO;
view9.selected = NO;
view9.showsTouchWhenHighlighted = NO;
view9.tag = 0;
view9.userInteractionEnabled = YES;
[view9 setTitle:@"Test" forState:UIControlStateDisabled];
[view9 setTitle:@"Test" forState:UIControlStateHighlighted];
[view9 setTitle:@"Test" forState:UIControlStateNormal];
[view9 setTitle:@"Test" forState:UIControlStateSelected];
[view9 setTitleColor:[UIColor colorWithRed:0.196 green:0.310 blue:0.522 alpha:1.000] forState:UIControlStateNormal];
[view9 setTitleColor:[UIColor colorWithRed:1.000 green:1.000 blue:1.000 alpha:1.000] forState:UIControlStateHighlighted];
[view9 setTitleColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateDisabled];
[view9 setTitleColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateSelected];
[view9 setTitleShadowColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateDisabled];
[view9 setTitleShadowColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateHighlighted];
[view9 setTitleShadowColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateNormal];
[view9 setTitleShadowColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateSelected];

[view6 addSubview:view8];
[view6 addSubview:view10];
[view6 addSubview:view11];
[view6 addSubview:view9];
[view14 addSubview:view12];
[view14 addSubview:view13];
[view6 addSubview:view14];
[view6 addSubview:view18];
[view6 addSubview:view19];
[view6 addSubview:view20];
[view23 addSubview:view25];
[view23 addSubview:view26];
[view23 addSubview:view27];
[view23 addSubview:view29];
[view23 addSubview:view28];
[view32 addSubview:view33];
[view32 addSubview:view34];
[view35 addSubview:view38];
[view35 addSubview:view39];
[view55 addSubview:view56];
[view41 addSubview:view55];
[view40 addSubview:view41];
[view40 addSubview:view43];
[view50 addSubview:view51];
[view50 addSubview:view52];
[view50 addSubview:view53];
[view40 addSubview:view50];
[view45 addSubview:view46];
[view45 addSubview:view48];
[view45 addSubview:view49];
[view40 addSubview:view45];
