//
//  processors.h
//  GUI App
//
//  Created by Travis Tilley on 12/7/11.
//  Copyright (c) 2011 Travis Tilley. All rights reserved.
//

#import "Processor.h"

#import "NSString+Nib2ObjcExtensions.h"
#import "NSNumber+Nib2ObjcExtensions.h"
#import "NSDictionary+Nib2ObjcExtensions.h"

#import "GLKViewControllerProcessor.h"
#import "GLKViewProcessor.h"
#import "MKMapViewProcessor.h"
#import "ProxyObjectProcessor.h"
#import "UIActivityIndicatorViewProcessor.h"
#import "UIBarButtonItemProcessor.h"
#import "UIBarItemProcessor.h"
#import "UIButtonProcessor.h"
#import "UIControlProcessor.h"
#import "UIDatePickerProcessor.h"
#import "UIGestureRecognizerProcessor.h"
#import "UIImageViewProcessor.h"
#import "UILabelProcessor.h"
#import "UILongPressGestureRecognizerProcessor.h"
#import "UINavigationBarProcessor.h"
#import "UINavigationItemProcessor.h"
#import "UIPageControlProcessor.h"
#import "UIPanGestureRecognizerProcessor.h"
#import "UIPickerViewProcessor.h"
#import "UIPinchGestureRecognizerProcessor.h"
#import "UIProgressViewProcessor.h"
#import "UIRotationGestureRecognizerProcessor.h"
#import "UIScrollViewProcessor.h"
#import "UISearchBarProcessor.h"
#import "UISegmentedControlProcessor.h"
#import "UISliderProcessor.h"
#import "UIStepperProcessor.h"
#import "UISwipeGestureRecognizerProcessor.h"
#import "UISwitchProcessor.h"
#import "UITabBarItemProcessor.h"
#import "UITabBarProcessor.h"
#import "UITableViewCellProcessor.h"
#import "UITableViewControllerProcessor.h"
#import "UITableViewProcessor.h"
#import "UITapGestureRecognizerProcessor.h"
#import "UITextFieldProcessor.h"
#import "UITextViewProcessor.h"
#import "UIToolbarProcessor.h"
#import "UIViewControllerProcessor.h"
#import "UIViewProcessor.h"
#import "UIWebViewProcessor.h"
